Added publishing junit reports

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -41,7 +41,11 @@ jobs:
         run: uv run pylint --fail-under=9 ./src
       - name: Run tests
         run: |
-          cd tests
-          uv run pytest --junitxml=../test-results/junit.xml
+          uv run pytest tests/ --junitxml=test-results/junit.xml
       - name: Test migrations
         run: uv run alembic upgrade head
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/test-results/junit.xml'
